### PR TITLE
Handle failures more gracefully.

### PR DESCRIPTION
**Pull request by guardbotmk3**
For Get, we add an exception type that contains the offset where the error
occurred. For put, we allow for serialization failures to occur and be handled.

### CODE REVIEW

**Review by minad — COMMENTED** [review]
Could you rewrite evalPut in terms of evalCatchPut or the other way round? Besides that :+1:

**Comment by guardbotmk3** [comment]
Yeah, I can do that.

**Comment by minad** [comment]
But when is put actually failing?

**Comment by guardbotmk3** [comment]
This allows you to write serializations that rely on invariants and to fail
if those invariants don't hold.

For example, if you want to serialize a bytestring of known length without
a length prefix, you can now fail if the length doesn't match the
expectation.

**Comment by minad** [comment]
Hmm I am not sure if I like that. I think this is some kind of abuse of the serialization layer. You should rather ensure that there is no invalid data with violated invariants or create some verifier which does the invariant checks before (you might not want that for performance reasons?).

In contrast f inside Get are perfectly fine and expected. Therefore handled. And your PR improved that which I like.

**Comment by minad** [comment]
A solution I would prefer would be to expose an additional class of runPutIO functions and you just use those and do the error handling outside. Maybe move those to an Internal module?

**Comment by guardbotmk3** [comment]
That's a reasonable compromise. If your serialization can fail, run it in
IO and catch the errors yourself.

I'll make that part of the internals split, and leave only GetExceptions in
this PR.

**Comment by minad** [comment]
Sounds good!

**Comment by guardbotmk3** [comment]
OK, I stripped out Put failures.

**Comment by minad** [comment]
> OK, I stripped out Put failures.

I am not seeing this. Did you force push?

**Comment by guardbotmk3** [comment]
Sorry, you should see it now.

**Comment by minad** [comment]
looks good. thx.

**Pull request merged**
